/* ============================================
   meta.ts — 컴포넌트 출처 표기 (자동 생성)
   ============================================
   ⚠️ 이 파일은 `node scripts-gen-meta.mjs`로 생성됩니다. 직접 고치지 마세요.
      원본은 data.js입니다. 손으로 적으면 3개월 뒤 문서와 어긋납니다.

   origin
     'custom'  — Vuetify 없이 직접 만듦
     'wrapped' — Vuetify 컴포넌트를 감쌈
*/

export type Origin = 'custom' | 'wrapped'

export interface ComponentMeta {
  name: string
  ko: string
  category: string
  origin: Origin
  vuetifyBase: string | null
  summary: { ko: string; en: string }
  reason: { ko: string; en: string }
  where: string
  since: string
}

export const meta: ComponentMeta[] = [
  {
    name: 'DsButton',
    ko: '버튼',
    category: 'action',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '액션을 실행하는 기본 버튼.', en: '' },
    reason: {
      ko: '시각이 전부인 컴포넌트라 직접 만듭니다. 직접 만든 버튼은 Vuetify와 특이도 싸움이 일어나지 않습니다.',
      en: 'Purely visual; building it ourselves avoids specificity wars with Vuetify.',
    },
    where: '모든 화면의 액션. primary는 화면당 하나만.',
    since: '0.1.0',
  },
  {
    name: 'DsMenu',
    ko: '메뉴',
    category: 'action',
    origin: 'wrapped',
    vuetifyBase: 'VMenu',
    summary: { ko: '클릭하면 열리는 드롭다운 메뉴.', en: '' },
    reason: {
      ko: '뷰포트 경계에서 위치를 뒤집는 포지셔닝과 키보드 네비게이션을 직접 만들기 어렵습니다. Vuetify의 VMenu를 유지하고 안쪽 면만 우리 스타일로 바꿉니다.',
      en: 'Viewport-aware positioning and keyboard nav are hard to rebuild; keep VMenu, restyle the panel.',
    },
    where: '테이블 행 액션, 프로필 메뉴, 더보기.',
    since: '0.1.0',
  },
  {
    name: 'DsAvatar',
    ko: '아바타',
    category: 'content',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '사람 또는 에이전트를 나타내는 원형 표식.', en: '' },
    reason: {
      ko: '이니셜 표시와 겹침 그룹이 전부인 시각 컴포넌트입니다.',
      en: 'Initials and overlap groups — purely visual.',
    },
    where: '사용자·에이전트 표시. 이름과 함께 씁니다.',
    since: '0.1.0',
  },
  {
    name: 'DsCard',
    ko: '카드',
    category: 'content',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '콘텐츠를 담는 면(Surface).', en: '' },
    reason: {
      ko: 'VCard의 elevation 시스템이 필요 없습니다. 우리는 그림자 대신 1px 보더로만 구분합니다.',
      en: 'No need for VCard elevation; we separate with 1px borders only.',
    },
    where: '대시보드 통계, 설정 그룹.',
    since: '0.1.0',
  },
  {
    name: 'DsDivider',
    ko: '구분선',
    category: 'content',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '내용을 나누는 1px 선.', en: '' },
    reason: {
      ko: '시각 요소를 절제한 화면에서는 그림자 대신 이것으로 영역을 나눕니다.',
      en: 'Our primary separation device in a shadowless system.',
    },
    where: '설정 그룹 사이, 대화의 날짜 구분.',
    since: '0.1.0',
  },
  {
    name: 'DsCitationChip',
    ko: '인용 칩',
    category: 'content',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '에이전트 응답의 근거 출처를 가리키는 번호 칩.', en: '' },
    reason: {
      ko: 'Vuetify에 근거 인용 개념이 없습니다. 에이전트 제품의 신뢰도를 만드는 핵심 요소입니다.',
      en: 'No citation concept in Vuetify; core to agent trustworthiness.',
    },
    where: '에이전트 응답에서 근거가 있는 주장 뒤.',
    since: '0.1.0',
  },
  {
    name: 'DsEmptyState',
    ko: '빈 상태',
    category: 'content',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '데이터가 없을 때 보여주는 화면.', en: '' },
    reason: {
      ko: 'Vuetify에 없습니다. 시각 요소를 절제한 화면에서는 빈 화면이 "미완성"처럼 보이기 쉬워 특히 중요합니다.',
      en: 'Not in Vuetify; critical in a minimal system where blank reads as broken.',
    },
    where: '모든 목록·테이블·검색의 빈 상태. 다음 행동을 반드시 제안.',
    since: '0.1.0',
  },
  {
    name: 'DsInput',
    ko: '입력 필드',
    category: 'input',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '한 줄 텍스트 입력.', en: '' },
    reason: {
      ko: 'VTextField는 VField 래퍼가 5~6겹이라 겹을 벗기는 비용이 새로 만드는 비용보다 큽니다.',
      en: 'VTextField nests VField 5-6 layers deep; unwrapping costs more than rebuilding.',
    },
    where: '한 줄 입력 전부. 에러 상태는 필수.',
    since: '0.1.0',
  },
  {
    name: 'DsSelect',
    ko: '선택',
    category: 'input',
    origin: 'wrapped',
    vuetifyBase: 'VSelect',
    summary: { ko: '옵션 목록에서 하나 또는 여러 개를 고릅니다.', en: '' },
    reason: {
      ko: '옵션 목록 포지셔닝·키보드 선택·다중 선택 동작이 복잡합니다. VSelect를 유지하고 필드 외형만 바꿉니다.',
      en: 'List positioning, keyboard selection, multi-select are complex; keep VSelect, restyle the field.',
    },
    where: '옵션 10개 이하의 선택. 그 이상은 Autocomplete.',
    since: '0.1.0',
  },
  {
    name: 'DsChip',
    ko: '칩',
    category: 'input',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '선택된 항목을 표시하고 제거합니다.', en: '' },
    reason: {
      ko: 'VChip보다 훨씬 단순한 형태만 필요합니다.',
      en: 'We need a far simpler shape than VChip.',
    },
    where: '활성 필터 표시, 첨부 파일 목록, 선택된 태그.',
    since: '0.1.0',
  },
  {
    name: 'DsAgentInput',
    ko: '에이전트 입력창',
    category: 'input',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '에이전트에게 메시지를 보내는 입력창.', en: '' },
    reason: {
      ko: 'Vuetify에 없습니다. 여러 줄 자동 확장, 파일 첨부, 슬래시 명령, Enter 전송이 한 컴포넌트에 필요합니다.',
      en: 'Not in Vuetify. Auto-grow, attachments, slash commands, Enter-to-send in one component.',
    },
    where: '챗 화면 하단. Enter 전송, Shift+Enter 줄바꿈.',
    since: '0.1.0',
  },
  {
    name: 'DsBadge',
    ko: '배지',
    category: 'feedback',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '상태를 표시하는 작은 읽기 전용 라벨.', en: '' },
    reason: {
      ko: 'VChip으로 대체 가능하지만 필요한 형태가 훨씬 단순합니다.',
      en: 'Simpler than VChip for our needs.',
    },
    where: '테이블 상태 열, 목록 항목의 상태 표시. 읽기 전용.',
    since: '0.1.0',
  },
  {
    name: 'DsSkeleton',
    ko: '스켈레톤',
    category: 'feedback',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '데이터 로딩 중 콘텐츠의 자리를 미리 보여줍니다.', en: '' },
    reason: {
      ko: 'VSkeletonLoader는 프리셋 타입이 많아 무겁습니다. 우리는 3가지 형태만 필요합니다.',
      en: 'VSkeletonLoader ships many presets; we need only three shapes.',
    },
    where: '목록·테이블의 로딩 상태. 에이전트 응답 대기에는 쓰지 않습니다.',
    since: '0.1.0',
  },
  {
    name: 'DsToast',
    ko: '토스트',
    category: 'feedback',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '작업 결과를 잠깐 알리는 알림.', en: '' },
    reason: {
      ko: 'VSnackbar를 쓸 수도 있지만 큐 관리를 우리가 하고 싶고 시각이 단순합니다.',
      en: 'We manage the queue ourselves; visuals are simple.',
    },
    where: 'Snackbar의 시각 부분. 큐 관리가 필요하면 Snackbar를 쓰세요.',
    since: '0.1.0',
  },
  {
    name: 'DsDialog',
    ko: '다이얼로그',
    category: 'overlay',
    origin: 'wrapped',
    vuetifyBase: 'VDialog',
    summary: { ko: '화면 위에 떠서 흐름을 멈추는 창.', en: '' },
    reason: {
      ko: '포커스 트랩, 배경 스크롤 락, ESC 처리, 접근성 속성을 직접 만들기 어렵습니다. VDialog를 유지하고 내부 면만 우리 스타일로 바꿉니다.',
      en: 'Focus trap, scroll lock, ESC handling and a11y are hard to rebuild; keep VDialog, restyle the panel.',
    },
    where: '되돌릴 수 없는 확인, 흐름을 멈춰야 하는 입력.',
    since: '0.1.0',
  },
  {
    name: 'DsTooltip',
    ko: '툴팁',
    category: 'overlay',
    origin: 'wrapped',
    vuetifyBase: 'VTooltip',
    summary: { ko: '요소에 마우스를 올리면 뜨는 짧은 설명.', en: '' },
    reason: {
      ko: '지연 표시, 포지셔닝, 터치 기기 대응을 Vuetify가 이미 처리합니다.',
      en: 'Delay, positioning and touch handling already solved by Vuetify.',
    },
    where: '아이콘 버튼 설명, 잘린 텍스트 전체 보기.',
    since: '0.1.0',
  },
  {
    name: 'DsDataTable',
    ko: '데이터 테이블',
    category: 'data',
    origin: 'wrapped',
    vuetifyBase: 'VDataTable',
    summary: { ko: '정렬·페이지네이션이 되는 데이터 목록.', en: '' },
    reason: {
      ko: '정렬, 페이지네이션, 행 선택, 가상 스크롤을 직접 만드는 것은 비현실적입니다. VDataTable을 그대로 쓰고 시각만 우리 것으로 덮습니다.',
      en: 'Sorting, pagination, selection, virtualization are impractical to rebuild; keep VDataTable and restyle.',
    },
    where: '감사 로그, 에이전트 목록, 실행 이력 — 열이 고정된 데이터.',
    since: '0.1.0',
  },
  {
    name: 'DsFileGrid',
    ko: '파일 그리드',
    category: 'data',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '드라이브의 그리드(카드) 보기.', en: '' },
    reason: {
      ko: 'Vuetify에 파일 브라우저 개념이 없습니다.',
      en: 'No file browser concept in Vuetify.',
    },
    where: '드라이브 그리드 보기 — 훑어보기용.',
    since: '0.1.0',
  },
  {
    name: 'DsFileRow',
    ko: '파일 행',
    category: 'data',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '드라이브의 리스트 보기 한 줄.', en: '' },
    reason: {
      ko: 'Vuetify에 파일 브라우저 개념이 없습니다.',
      en: 'No file browser concept in Vuetify.',
    },
    where: '드라이브 리스트 보기 — 세부 비교용.',
    since: '0.1.0',
  },
  {
    name: 'DsSearchResult',
    ko: '검색 결과',
    category: 'data',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '검색 결과 한 건.', en: '' },
    reason: {
      ko: 'Vuetify에 검색 결과 개념이 없습니다.',
      en: 'No search result concept in Vuetify.',
    },
    where: '검색 화면, 문서 찾기 결과.',
    since: '0.1.0',
  },
  {
    name: 'DsChatMessage',
    ko: '채팅 메시지',
    category: 'agent',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '대화의 메시지 한 건.', en: '' },
    reason: {
      ko: 'Vuetify에 대화형 메시지 컴포넌트가 없습니다. 스트리밍 중 높이가 변하고 역방향 스크롤 앵커링이 필요해 VCard로 대체할 수 없습니다.',
      en: 'No conversational message component in Vuetify. Streaming height changes and reverse scroll anchoring cannot be supported by VCard.',
    },
    where: '챗 화면. 툴콜은 본문 위에 — 근거가 답보다 먼저.',
    since: '0.1.0',
  },
  {
    name: 'DsStreamingText',
    ko: '스트리밍 텍스트',
    category: 'agent',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '응답이 실시간으로 흘러나오는 중임을 나타냅니다.', en: '' },
    reason: {
      ko: 'Vuetify에 없습니다. 토큰 단위로 텍스트가 늘어나는 동안 커서를 유지합니다.',
      en: 'Not in Vuetify; keeps a caret while tokens stream in.',
    },
    where: '스트리밍 중인 응답 본문.',
    since: '0.1.0',
  },
  {
    name: 'DsThinkingIndicator',
    ko: '추론 표시',
    category: 'agent',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '에이전트가 생각하는 중임을 알립니다.', en: '' },
    reason: {
      ko: 'Vuetify에 없습니다. 원칙 1 — 빈 스피너 대신 무엇을 하고 있는지 말로 보여줍니다.',
      en: 'Not in Vuetify. Principle 1 — words, not a bare spinner.',
    },
    where: '에이전트 대기 전부. 10초 이상이면 문구를 단계에 맞게 갱신.',
    since: '0.1.0',
  },
  {
    name: 'DsToolCallStep',
    ko: '툴콜 단계',
    category: 'agent',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '에이전트가 도구를 실행하는 과정 한 단계.', en: '' },
    reason: {
      ko: 'Vuetify에 없습니다. 에이전트 제품에서 "일하고 있음"을 보여주는 가장 중요한 요소입니다.',
      en: 'Not in Vuetify; the key device for showing the agent is working.',
    },
    where: '에이전트가 도구를 쓸 때마다. 실패한 단계도 그대로 보여줍니다.',
    since: '0.1.0',
  },
  {
    name: 'DsArtifactPanel',
    ko: '산출물 패널',
    category: 'agent',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '에이전트가 만든 산출물(코드·문서·표)을 대화 옆에 보여줍니다.', en: '' },
    reason: {
      ko: 'Vuetify에 없습니다. 긴 산출물을 대화 흐름에서 분리해야 둘 다 읽을 수 있습니다.',
      en: 'Not in Vuetify; long outputs must live outside the conversation flow.',
    },
    where: '20줄이 넘는 에이전트 산출물 — 코드·문서·표.',
    since: '0.1.0',
  },
  {
    name: 'DsIcon',
    ko: '아이콘',
    category: 'content',
    origin: 'wrapped',
    vuetifyBase: 'Lucide',
    summary: { ko: '아이콘 하나를 그립니다.', en: '' },
    reason: {
      ko: '아이콘 세트가 섞이면 굵기와 광학 크기가 달라 같은 줄에서 어긋나 보입니다. Lucide 하나로 고정하고, Lucide 이름이 아니라 우리 어휘(의미 이름)로 부릅니다 — 나중에 세트를 바꿔도 화면 코드는 그대로입니다.',
      en: 'Mixed icon sets misalign due to differing stroke and optical size. Fixed to Lucide, addressed by semantic name so the set can be swapped without touching screens.',
    },
    where: '아이콘이 필요한 모든 곳. 의미 이름으로 부르고, 없으면 vue/icons.ts에 등록합니다.',
    since: '0.1.0',
  },
  {
    name: 'DsIconButton',
    ko: '아이콘 버튼',
    category: 'action',
    origin: 'wrapped',
    vuetifyBase: 'VBtn',
    summary: { ko: '아이콘만 있는 버튼.', en: '' },
    reason: {
      ko: '아이콘 버튼은 크기·정렬·aria-label 규칙이 화면마다 어긋나기 쉽습니다. 하나로 고정합니다.',
      en: 'Size, alignment and aria-label drift across screens; fix them once.',
    },
    where: '테이블 행 끝 ⋯, 툴바, 입력창 부가 버튼.',
    since: '0.1.0',
  },
  {
    name: 'DsButtonGroup',
    ko: '버튼 그룹',
    category: 'action',
    origin: 'wrapped',
    vuetifyBase: 'VBtnToggle',
    summary: { ko: '서로 배타적인 보기 전환.', en: '' },
    reason: {
      ko: '라디오 버튼은 무겁고 탭은 과합니다. 그 중간 크기의 전환이 필요합니다.',
      en: 'Radios are heavy, tabs too prominent; this is the middle weight.',
    },
    where: '그리드/리스트 보기 전환, 기간(일·주·월), 밀도 전환.',
    since: '0.1.0',
  },
  {
    name: 'DsTabs',
    ko: '탭',
    category: 'action',
    origin: 'wrapped',
    vuetifyBase: 'VTabs',
    summary: { ko: '같은 대상의 여러 단면을 전환합니다.', en: '' },
    reason: {
      ko: 'Vuetify 기본 탭은 대문자 변환과 리플이 우리 기조와 맞지 않고, 건수 배지가 자주 필요합니다.',
      en: 'Default uppercase + ripple clash with our tone; count badges are frequently needed.',
    },
    where: '상세 화면 섹션 전환(개요·활동·설정), 로그 수준 필터.',
    since: '0.1.0',
  },
  {
    name: 'DsBreadcrumbs',
    ko: '경로',
    category: 'action',
    origin: 'wrapped',
    vuetifyBase: 'VBreadcrumbs',
    summary: { ko: '현재 위치의 계층 경로.', en: '' },
    reason: {
      ko: '구분자 모양과 마지막 항목 강조 규칙을 고정합니다.',
      en: 'Fix separator and last-item emphasis.',
    },
    where: '드라이브 폴더 경로, 설정 하위 페이지.',
    since: '0.1.0',
  },
  {
    name: 'DsPagination',
    ko: '페이지네이션',
    category: 'data',
    origin: 'wrapped',
    vuetifyBase: 'VPagination',
    summary: { ko: '긴 목록을 페이지로 나눕니다.', en: '' },
    reason: {
      ko: 'Vuetify 기본은 크고 그림자가 있습니다. 조용하게 낮춥니다.',
      en: 'Default is large and elevated; we quiet it down.',
    },
    where: '테이블 하단, 검색 결과 하단.',
    since: '0.1.0',
  },
  {
    name: 'DsNavList',
    ko: '내비게이션 목록',
    category: 'action',
    origin: 'wrapped',
    vuetifyBase: 'VList',
    summary: { ko: '좌측 사이드바 메뉴.', en: '' },
    reason: {
      ko: '사이드바는 모든 화면에 나오는데 매번 다르게 만들어집니다. 아이콘·배지·활성 표시를 고정합니다.',
      en: 'Sidebars appear everywhere and drift; fix icon, badge and active styling.',
    },
    where: '앱 좌측 사이드바, 설정 좌측 메뉴.',
    since: '0.1.0',
  },
  {
    name: 'DsStepper',
    ko: '단계 표시',
    category: 'action',
    origin: 'wrapped',
    vuetifyBase: 'VStepper',
    summary: { ko: '여러 단계로 나뉜 흐름.', en: '' },
    reason: {
      ko: '마법사 UI를 매번 새로 만들면 단계 표시가 제각각이 됩니다.',
      en: 'Wizards drift without a fixed step indicator.',
    },
    where: '에이전트 생성 마법사, 온보딩, 다단계 폼.',
    since: '0.1.0',
  },
  {
    name: 'DsTextarea',
    ko: '여러 줄 입력',
    category: 'input',
    origin: 'wrapped',
    vuetifyBase: 'VTextarea',
    summary: { ko: '여러 줄 텍스트 입력.', en: '' },
    reason: {
      ko: 'auto-grow와 라벨·에러 규칙을 Input과 똑같이 맞추기 위해 감쌉니다.',
      en: 'Wrapped so auto-grow, label and error rules match DsInput exactly.',
    },
    where: '설명·메모 입력, 프롬프트 편집. (대화 입력은 AgentInput)',
    since: '0.1.0',
  },
  {
    name: 'DsAutocomplete',
    ko: '검색 선택',
    category: 'input',
    origin: 'wrapped',
    vuetifyBase: 'VAutocomplete',
    summary: { ko: '검색해서 고르는 선택.', en: '' },
    reason: {
      ko: '검색·필터링을 직접 만들면 한글 조합 입력에서 깨집니다. Vuetify 구현을 유지합니다.',
      en: 'Hand-rolled filtering breaks on Korean IME composition; keep Vuetify.',
    },
    where: '옵션이 10개를 넘는 선택 — 사용자 지정, 태그, 폴더 이동.',
    since: '0.1.0',
  },
  {
    name: 'DsCheckbox',
    ko: '체크박스',
    category: 'input',
    origin: 'wrapped',
    vuetifyBase: 'VCheckbox',
    summary: { ko: '켜고 끄는 선택. 저장 버튼과 함께 씁니다.', en: '' },
    reason: {
      ko: '부분 선택(indeterminate) 상태가 테이블 전체 선택에 반드시 필요한데 직접 만들면 빠뜨립니다.',
      en: 'Indeterminate state is required for table select-all and is easy to miss.',
    },
    where: '테이블 다중 선택, 약관 동의, 저장 버튼이 있는 설정.',
    since: '0.1.0',
  },
  {
    name: 'DsSwitch',
    ko: '스위치',
    category: 'input',
    origin: 'wrapped',
    vuetifyBase: 'VSwitch',
    summary: { ko: '즉시 반영되는 on/off.', en: '' },
    reason: {
      ko: 'Checkbox와 혼용되면 "저장을 눌러야 하나"가 매번 헷갈립니다. 즉시 반영 = Switch로 고정합니다.',
      en: 'Mixing with checkbox confuses save semantics; switch always means instant.',
    },
    where: '즉시 적용되는 on/off — 에이전트 활성화, 자동 실행.',
    since: '0.1.0',
  },
  {
    name: 'DsRadioGroup',
    ko: '라디오 그룹',
    category: 'input',
    origin: 'wrapped',
    vuetifyBase: 'VRadioGroup',
    summary: { ko: '여러 선택지 중 하나.', en: '' },
    reason: {
      ko: '항목마다 부연 설명이 필요한 경우가 많아 hint를 구조에 포함시켰습니다.',
      en: 'Per-option hints are common; baked into the structure.',
    },
    where: '배타적 설정 — 보존 기간, 공개 범위.',
    since: '0.1.0',
  },
  {
    name: 'DsSlider',
    ko: '슬라이더',
    category: 'input',
    origin: 'wrapped',
    vuetifyBase: 'VSlider',
    summary: { ko: '범위 안에서 값을 조정합니다.', en: '' },
    reason: {
      ko: '현재 값 표시가 기본으로 없어서 매번 따로 붙이게 됩니다. 라벨에 통합했습니다.',
      en: 'Current value display is always added ad hoc; folded into the label.',
    },
    where: '임계값 조정 — 신뢰도 컷오프, 결과 개수.',
    since: '0.1.0',
  },
  {
    name: 'DsFileInput',
    ko: '파일 선택',
    category: 'input',
    origin: 'wrapped',
    vuetifyBase: 'VFileInput',
    summary: { ko: '파일을 고르거나 끌어다 놓습니다.', en: '' },
    reason: {
      ko: '기본 클립 아이콘과 머티리얼 스타일이 우리 기조와 맞지 않습니다.',
      en: 'Default paperclip and material styling clash with our tone.',
    },
    where: '문서 업로드, 로고 교체.',
    since: '0.1.0',
  },
  {
    name: 'DsDatePicker',
    ko: '날짜 선택',
    category: 'input',
    origin: 'wrapped',
    vuetifyBase: 'VDatePicker',
    summary: { ko: '달력에서 날짜를 고릅니다.', en: '' },
    reason: {
      ko: '달력을 직접 만드는 것은 비현실적입니다 — 로케일, 윤년, 키보드 이동, 접근성.',
      en: 'Building a calendar is impractical: locale, leap years, keyboard nav, a11y.',
    },
    where: '감사 로그 기간 필터, 스케줄 설정.',
    since: '0.1.0',
  },
  {
    name: 'DsAlert',
    ko: '알림',
    category: 'feedback',
    origin: 'wrapped',
    vuetifyBase: 'VAlert',
    summary: { ko: '화면에 머무는 상태 알림.', en: '' },
    reason: {
      ko: 'Toast와 역할이 섞이면 중요한 정보가 사라져 버립니다. Alert는 사라지지 않는 알림으로 고정합니다.',
      en: 'Mixing with Toast loses important information; Alert is the persistent one.',
    },
    where: '폼 상단 검증 요약, 권한 부족 안내, 한도 경고. 사라지면 안 되는 정보.',
    since: '0.1.0',
  },
  {
    name: 'DsBanner',
    ko: '배너',
    category: 'feedback',
    origin: 'wrapped',
    vuetifyBase: 'VBanner',
    summary: { ko: '페이지 전체에 해당하는 공지.', en: '' },
    reason: {
      ko: 'Alert는 영역 단위, Banner는 페이지 전체 단위입니다. 이 구분이 없으면 둘 다 남발됩니다.',
      en: 'Alert is regional, Banner is page-wide; without the distinction both get overused.',
    },
    where: '화면 최상단 전역 공지 — 점검 예정, 요금제 만료.',
    since: '0.1.0',
  },
  {
    name: 'DsProgressBar',
    ko: '진행 막대',
    category: 'feedback',
    origin: 'wrapped',
    vuetifyBase: 'VProgressLinear',
    summary: { ko: '진행률을 아는 작업의 막대.', en: '' },
    reason: {
      ko: '진행률 숫자를 매번 따로 붙이게 되어 라벨에 통합했습니다.',
      en: 'The percentage label is always added ad hoc; folded in.',
    },
    where: '업로드·일괄 처리 — 진행률을 아는 경우만. 모르면 ThinkingIndicator.',
    since: '0.1.0',
  },
  {
    name: 'DsSpinner',
    ko: '스피너',
    category: 'feedback',
    origin: 'wrapped',
    vuetifyBase: 'VProgressCircular',
    summary: { ko: '아주 짧은 대기 표시.', en: '' },
    reason: {
      ko: '크기·굵기가 제각각이 되기 쉬워 고정합니다. 2초 이내 대기 전용입니다.',
      en: 'Size and stroke drift; fixed. For sub-2-second waits only.',
    },
    where: '버튼 내부, 인라인 짧은 대기(2초 이내). 에이전트 작업에는 쓰지 않습니다.',
    since: '0.1.0',
  },
  {
    name: 'DsSnackbar',
    ko: '스낵바',
    category: 'feedback',
    origin: 'wrapped',
    vuetifyBase: 'VSnackbar',
    summary: { ko: '떴다가 사라지는 알림.', en: '' },
    reason: {
      ko: 'Toast는 생김새만 담당합니다. 실제로 떠서 시간이 지나면 사라지는 동작이 필요합니다.',
      en: 'DsToast is visual only; this adds real appearance and timeout behavior.',
    },
    where: '저장·삭제 결과 알림. 후속 액션은 하나까지.',
    since: '0.1.0',
  },
  {
    name: 'DsList',
    ko: '목록',
    category: 'data',
    origin: 'wrapped',
    vuetifyBase: 'VList',
    summary: { ko: '열이 고정되지 않은 항목 목록.', en: '' },
    reason: {
      ko: '열이 고정되지 않은 목록에 테이블은 과합니다. 그 중간 단계가 필요합니다.',
      en: 'A table is overkill when columns are not fixed; this is the middle ground.',
    },
    where: '설정 항목, 선택 가능한 항목 나열. (파일은 FileRow, 고정 열은 DataTable)',
    since: '0.1.0',
  },
  {
    name: 'DsTreeview',
    ko: '트리',
    category: 'data',
    origin: 'wrapped',
    vuetifyBase: 'VTreeview',
    summary: { ko: '계층 구조를 펼쳐서 봅니다.', en: '' },
    reason: {
      ko: '펼침 상태·키보드 이동·중첩 선택을 직접 만들면 깊이가 늘 때 무너집니다.',
      en: 'Expansion state, keyboard nav and nested selection break at depth if hand-rolled.',
    },
    where: '드라이브 폴더 트리, 문서 목차, 조직도.',
    since: '0.1.0',
  },
  {
    name: 'DsTimeline',
    ko: '타임라인',
    category: 'data',
    origin: 'wrapped',
    vuetifyBase: 'VTimeline',
    summary: { ko: '시간순 이력.', en: '' },
    reason: {
      ko: '시간순 이력을 평범한 목록으로 만들면 "무엇이 먼저인지"가 읽히지 않습니다.',
      en: 'Chronology is lost when history is rendered as a plain list.',
    },
    where: '문서 변경 이력, 에이전트 실행 이력, 승인 흐름.',
    since: '0.1.0',
  },
  {
    name: 'DsAccordion',
    ko: '아코디언',
    category: 'data',
    origin: 'wrapped',
    vuetifyBase: 'VExpansionPanels',
    summary: { ko: '접었다 펴는 영역.', en: '' },
    reason: {
      ko: '원칙 4 — 근거를 접을 수는 있어도 없애지 않습니다. 그 "접기"의 구현체입니다.',
      en: 'Principle 4 — evidence may be collapsed, never removed. This is that collapse.',
    },
    where: '툴콜 원본 페이로드, 고급 설정, FAQ. (원칙 4의 "접기")',
    since: '0.1.0',
  },
  {
    name: 'DsLink',
    ko: '링크',
    category: 'action',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '본문 속 이동.', en: '' },
    reason: {
      ko: '브랜드색·호버 밑줄·포커스 링 규칙을 고정합니다.',
      en: 'Fixes brand color, hover underline and focus ring.',
    },
    where: '본문·설명 속 이동. 동작 실행은 Button.',
    since: '0.1.0',
  },
  {
    name: 'DsKbd',
    ko: '키 표기',
    category: 'content',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '키보드 키를 표기합니다.', en: '' },
    reason: {
      ko: '단축키 안내의 시각을 고정합니다.',
      en: 'Fixes shortcut notation.',
    },
    where: '단축키 안내 — 팔레트 항목, 툴팁, 문서.',
    since: '0.1.0',
  },
  {
    name: 'DsCode',
    ko: '코드',
    category: 'content',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '인라인 · 블록 코드.', en: '' },
    reason: {
      ko: '고정폭·복사 버튼·tabular 숫자를 한 곳에 고정합니다.',
      en: 'Mono, copy button, tabular digits in one place.',
    },
    where: '식별자·페이로드·API 응답 표기.',
    since: '0.1.0',
  },
  {
    name: 'DsStatusDot',
    ko: '상태 점',
    category: 'feedback',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '텍스트 없는 최소 상태 표시.', en: '' },
    reason: {
      ko: '아바타 모서리·탭 이름 옆처럼 배지가 들어가지 않는 자리가 있습니다.',
      en: 'For spots too small for a badge.',
    },
    where: '아바타 모서리·탭 이름 옆 — 배지가 안 들어가는 최소 자리.',
    since: '0.1.0',
  },
  {
    name: 'DsTimestamp',
    ko: '시각',
    category: 'content',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '용어집 규칙이 내장된 시각 표기.', en: '' },
    reason: {
      ko: '"7일 이내 상대, 이후 절대·고정폭" 규칙을 화면마다 다시 구현하지 않게 합니다.',
      en: 'Encodes the relative/absolute time rule once.',
    },
    where: '테이블 시각 열, 메시지 시각, 실행 기록.',
    since: '0.1.0',
  },
  {
    name: 'DsMetaList',
    ko: '메타 목록',
    category: 'content',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '키-값 정보 나열.', en: '' },
    reason: {
      ko: '상세 패널의 라벨 폭·정렬이 화면마다 달라지는 것을 막습니다.',
      en: 'Fixes the key-value layout of detail panels.',
    },
    where: '상세 패널의 키-값 — 이벤트·문서·에이전트 속성.',
    since: '0.1.0',
  },
  {
    name: 'DsSearchField',
    ko: '검색 입력',
    category: 'input',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '검색 전용 입력 — 돋보기 · 지우기 · 단축키 힌트 · 로딩.', en: '' },
    reason: {
      ko: '검색창의 부속(아이콘·⌘K·클리어)이 화면마다 제각각이 되는 것을 막습니다.',
      en: 'One search affordance set, everywhere.',
    },
    where: '목록 상단·GNB 검색. 전역이면 CommandPalette와 연동.',
    since: '0.1.0',
  },
  {
    name: 'DsSystemMessage',
    ko: '시스템 메시지',
    category: 'agent',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '대화 속 시스템 알림.', en: '' },
    reason: {
      ko: '"대화가 요약되었습니다" 같은 안내는 참여자 발화가 아닙니다 — 중앙의 낮은 톤으로 구분합니다.',
      en: 'System notices are not utterances; centered low-key row.',
    },
    where: '대화 스트림 속 시스템 안내 — 요약됨·초기화됨.',
    since: '0.1.0',
  },
  {
    name: 'DsToolbar',
    ko: '툴바',
    category: 'action',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '컨트롤 줄 정렬 규약.', en: '' },
    reason: {
      ko: '컨트롤 줄의 높이·간격·구분이 화면마다 달라지는 것을 막습니다. 밀한 맥락 = sm 규칙의 집.',
      en: 'One control-row convention.',
    },
    where: '테이블 위 컨트롤 줄, 상세 헤더 액션 줄.',
    since: '0.1.0',
  },
  {
    name: 'DsVisuallyHidden',
    ko: '시각 숨김',
    category: 'content',
    origin: 'custom',
    vuetifyBase: null,
    summary: { ko: '화면에는 없고 스크린리더에는 읽힘.', en: '' },
    reason: {
      ko: '시각적으로 자명한 맥락을 보조기기에 전달할 표준 방법이 필요합니다.',
      en: 'Standard SR-only text.',
    },
    where: '아이콘·시각 정보에 보조기기용 설명을 붙일 때.',
    since: '0.1.0',
  },
  {
    name: 'DsNumberInput',
    ko: '숫자 입력',
    category: 'input',
    origin: 'wrapped',
    vuetifyBase: 'VNumberInput',
    summary: { ko: '스텝 버튼이 있는 숫자 입력.', en: '' },
    reason: {
      ko: '스텝 버튼, ↑↓ 키, min/max 클램프를 직접 만들면 IME·붙여넣기에서 깨집니다.',
      en: 'Steppers, arrow keys and clamping are easy to get wrong.',
    },
    where: '재시도 횟수·한도·개수 — 스텝이 필요한 숫자.',
    since: '0.1.0',
  },
  {
    name: 'DsCombobox',
    ko: '자유 태그 입력',
    category: 'input',
    origin: 'wrapped',
    vuetifyBase: 'VCombobox',
    summary: { ko: '목록에 없는 값도 입력하는 태그 입력.', en: '' },
    reason: {
      ko: '자유 입력 + 제안 + 칩 관리 + 한글 조합을 함께 처리해야 합니다.',
      en: 'Free entry + suggestions + chips + IME.',
    },
    where: '태그·수신자 — 자유 입력 + 제안.',
    since: '0.1.0',
  },
  {
    name: 'DsPopover',
    ko: '팝오버',
    category: 'overlay',
    origin: 'wrapped',
    vuetifyBase: 'VMenu',
    summary: { ko: '클릭으로 여는 내용 패널.', en: '' },
    reason: {
      ko: 'Tooltip보다 길고 Dialog보다 가벼운 정보가 있습니다. 포지셔닝은 VMenu가 처리합니다.',
      en: 'Between tooltip and dialog; VMenu does positioning.',
    },
    where: '아이콘 옆 부가 설명, 짧은 미리보기 — 클릭으로 엶.',
    since: '0.1.0',
  },
  {
    name: 'DsHoverCard',
    ko: '호버 카드',
    category: 'overlay',
    origin: 'wrapped',
    vuetifyBase: 'VMenu',
    summary: { ko: '올리면 뜨는 미리보기.', en: '' },
    reason: {
      ko: '지연·포지셔닝·유지 판정을 직접 만들면 깜빡입니다.',
      en: 'Delay and positioning flicker if hand-rolled.',
    },
    where: '사용자·문서 이름 위 미리보기 — 부가 정보만.',
    since: '0.1.0',
  },
  {
    name: 'DsCommandPalette',
    ko: '명령 팔레트',
    category: 'overlay',
    origin: 'wrapped',
    vuetifyBase: 'VDialog',
    summary: { ko: '⌘K — 어디서든 검색·실행.', en: '' },
    reason: {
      ko: '검색 + 키보드 탐색 + 실행을 하나로. 포커스 트랩은 VDialog가 처리합니다.',
      en: 'Search, keyboard nav and execute in one; VDialog traps focus.',
    },
    where: '전역 ⌘K — 문서·에이전트·명령으로 점프.',
    since: '0.1.0',
  },
]

/** 이름으로 찾기 — 문서 배지 자동 렌더용 */
export const metaByName = Object.fromEntries(meta.map((m) => [m.name, m]))

/** 통계 */
export const metaStats = {
  total: meta.length,
  standalone: meta.filter((m) => m.origin === 'custom').length,
  vuetifyBased: meta.filter((m) => m.origin === 'wrapped').length,
}
